<?php

return [
    ['id' => 394, 'slug' => 'africa', 'name' => 'Africa', 'code' => null],
    ['id' => 1460, 'slug' => 'alemania', 'name' => 'Alemania', 'code' => 'DE'],
    ['id' => 132, 'slug' => 'argentina', 'name' => 'Argentina', 'code' => 'AR'],
    ['id' => 1182, 'slug' => 'australia', 'name' => 'Australia', 'code' => 'AU'],
    ['id' => 1298, 'slug' => 'azerbaijan', 'name' => 'Azerbaijan', 'code' => 'AZ'],
    ['id' => 1276, 'slug' => 'belorussia', 'name' => 'Belorussia', 'code' => 'BY'],
    ['id' => 235, 'slug' => 'bolivia', 'name' => 'Bolivia', 'code' => 'BO'],
    ['id' => 360, 'slug' => 'brasil', 'name' => 'Brasil', 'code' => 'BR'],
    ['id' => 384, 'slug' => 'canada', 'name' => 'Canadá', 'code' => 'CA'],
    ['id' => 1522, 'slug' => 'chequia', 'name' => 'Chequia', 'code' => 'CZ'],
    ['id' => 232, 'slug' => 'chile', 'name' => 'Chile', 'code' => 'CL'],
    ['id' => 216, 'slug' => 'colombia', 'name' => 'Colombia', 'code' => 'CO'],
    ['id' => 1619, 'slug' => 'costarica', 'name' => 'Costa Rica', 'code' => 'CR'],
    ['id' => 215, 'slug' => 'cuba', 'name' => 'Cuba', 'code' => 'CU'],
    ['id' => 1665, 'slug' => 'ecuador', 'name' => 'Ecuador', 'code' => 'EC'],
    ['id' => 1429, 'slug' => 'elsalvador', 'name' => 'El Salvador', 'code' => 'SV'],
    ['id' => 231, 'slug' => 'espana', 'name' => 'España', 'code' => 'ES'],
    ['id' => 233, 'slug' => 'estadosunidos', 'name' => 'Estados Unidos', 'code' => 'US'],
    ['id' => 1434, 'slug' => 'estonia', 'name' => 'Estonia', 'code' => 'EE'],
    ['id' => 411, 'slug' => 'francia', 'name' => 'Francia', 'code' => 'FR'],
    ['id' => 1284, 'slug' => 'georgia', 'name' => 'Georgia', 'code' => 'GE'],
    ['id' => 1407, 'slug' => 'guatemala', 'name' => 'Guatemala', 'code' => 'GT'],
    ['id' => 1622, 'slug' => 'honduras', 'name' => 'Honduras', 'code' => 'HN'],
    ['id' => 1576, 'slug' => 'india', 'name' => 'India', 'code' => 'IN'],
    ['id' => 1403, 'slug' => 'inglaterra', 'name' => 'Inglaterra', 'code' => 'GB'],
    ['id' => 1484, 'slug' => 'irlanda', 'name' => 'Irlanda', 'code' => 'IR'],
    ['id' => 1512, 'slug' => 'israel', 'name' => 'Israel', 'code' => 'IS'],
    ['id' => 370, 'slug' => 'italia', 'name' => 'Italia', 'code' => 'IT'],
    ['id' => 1291, 'slug' => 'kazakhstan', 'name' => 'Kazakhstan', 'code' => 'KZ'],
    ['id' => 393, 'slug' => 'medio-oriente', 'name' => 'Medio Oriente', 'code' => null],
    ['id' => 487, 'slug' => 'mexico', 'name' => 'México', 'code' => 'MX'],
    ['id' => 1497, 'slug' => 'palestina', 'name' => 'Palestina', 'code' => 'PS'],
    ['id' => 362, 'slug' => 'paraguay', 'name' => 'Paraguay', 'code' => 'PR'],
    ['id' => 369, 'slug' => 'peru', 'name' => 'Perú', 'code' => 'PE'],
    ['id' => 1524, 'slug' => 'polonia', 'name' => 'Polonia', 'code' => 'PL'],
    ['id' => 1586, 'slug' => 'portugal', 'name' => 'Portugal', 'code' => 'PT'],
    ['id' => 371, 'slug' => 'rusia', 'name' => 'Rusia', 'code' => 'RU'],
    ['id' => 372, 'slug' => 'ucrania', 'name' => 'Ucrania', 'code' => 'UA'],
    ['id' => 1412, 'slug' => 'uruguay', 'name' => 'Uruguay', 'code' => 'UY'],
    ['id' => 123, 'slug' => 'venezuela', 'name' => 'Venezuela', 'code' => 'VE']
];
