<?php

return [
    ['id' => 394, 'slug' => 'africa', 'name' => 'Africa', 'code' => null, 'order' => 21],
    ['id' => 1460, 'slug' => 'alemania', 'name' => 'Alemania', 'code' => 'DE', 'order' => 23],
    ['id' => 132, 'slug' => 'argentina', 'name' => 'Argentina', 'code' => 'AR', 'order' => 2],
    ['id' => 1182, 'slug' => 'australia', 'name' => 'Australia', 'code' => 'AU', 'order' => 24],
    ['id' => 1298, 'slug' => 'azerbaijan', 'name' => 'Azerbaijan', 'code' => 'AZ', 'order' => 28],
    ['id' => 1276, 'slug' => 'belorussia', 'name' => 'Belorussia', 'code' => 'BY', 'order' => 26],
    ['id' => 235, 'slug' => 'bolivia', 'name' => 'Bolivia', 'code' => 'BO', 'order' => 16],
    ['id' => 360, 'slug' => 'brasil', 'name' => 'Brasil', 'code' => 'BR', 'order' => 3],
    ['id' => 384, 'slug' => 'canada', 'name' => 'Canadá', 'code' => 'CA', 'order' => 11],
    ['id' => 1522, 'slug' => 'chequia', 'name' => 'Chequia', 'code' => 'CZ', 'order' => 20],
    ['id' => 232, 'slug' => 'chile', 'name' => 'Chile', 'code' => 'CL', 'order' => 4],
    ['id' => 216, 'slug' => 'colombia', 'name' => 'Colombia', 'code' => 'CO', 'order' => 17],
    ['id' => 1619, 'slug' => 'costarica', 'name' => 'Costa Rica', 'code' => 'CR', 'order' => 38],
    ['id' => 215, 'slug' => 'cuba', 'name' => 'Cuba', 'code' => 'CU', 'order' => 5],
    ['id' => 1665, 'slug' => 'ecuador', 'name' => 'Ecuador', 'code' => 'EC', 'order' => 18],
    ['id' => 1429, 'slug' => 'elsalvador', 'name' => 'El Salvador', 'code' => 'SV', 'order' => 31],
    ['id' => 231, 'slug' => 'espana', 'name' => 'España', 'code' => 'ES', 'order' => 6],
    ['id' => 233, 'slug' => 'estadosunidos', 'name' => 'Estados Unidos', 'code' => 'US', 'order' => 7],
    ['id' => 1434, 'slug' => 'estonia', 'name' => 'Estonia', 'code' => 'EE', 'order' => 32],
    ['id' => 411, 'slug' => 'francia', 'name' => 'Francia', 'code' => 'FR', 'order' => 8],
    ['id' => 1284, 'slug' => 'georgia', 'name' => 'Georgia', 'code' => 'GE', 'order' => 27],
    ['id' => 1407, 'slug' => 'guatemala', 'name' => 'Guatemala', 'code' => 'GT', 'order' => 29],
    ['id' => 1622, 'slug' => 'honduras', 'name' => 'Honduras', 'code' => 'HN', 'order' => 37],
    ['id' => 1576, 'slug' => 'india', 'name' => 'India', 'code' => 'IN', 'order' => 39],
    ['id' => 1403, 'slug' => 'inglaterra', 'name' => 'Inglaterra', 'code' => 'GB', 'order' => 25],
    ['id' => 1484, 'slug' => 'irlanda', 'name' => 'Irlanda', 'code' => 'IR', 'order' => 14],
    ['id' => 1512, 'slug' => 'israel', 'name' => 'Israel', 'code' => 'IS', 'order' => 15],
    ['id' => 370, 'slug' => 'italia', 'name' => 'Italia', 'code' => 'IT', 'order' => 12],
    ['id' => 1291, 'slug' => 'kazakhstan', 'name' => 'Kazakhstan', 'code' => 'KZ', 'order' => 40],
    ['id' => 393, 'slug' => 'medio-oriente', 'name' => 'Medio Oriente', 'code' => null, 'order' => 22],
    ['id' => 487, 'slug' => 'mexico', 'name' => 'México', 'code' => 'MX', 'order' => 9],
    ['id' => 1497, 'slug' => 'palestina', 'name' => 'Palestina', 'code' => 'PS', 'order' => 13],
    ['id' => 362, 'slug' => 'paraguay', 'name' => 'Paraguay', 'code' => 'PR', 'order' => 30],
    ['id' => 369, 'slug' => 'peru', 'name' => 'Perú', 'code' => 'PE', 'order' => 34],
    ['id' => 1524, 'slug' => 'polonia', 'name' => 'Polonia', 'code' => 'PL', 'order' => 36],
    ['id' => 1586, 'slug' => 'portugal', 'name' => 'Portugal', 'code' => 'PT', 'order' => 35],
    ['id' => 371, 'slug' => 'rusia', 'name' => 'Rusia', 'code' => 'RU', 'order' => 10],
    ['id' => 372, 'slug' => 'ucrania', 'name' => 'Ucrania', 'code' => 'UA', 'order' => 19],
    ['id' => 1412, 'slug' => 'uruguay', 'name' => 'Uruguay', 'code' => 'UY', 'order' => 33],
    ['id' => 123, 'slug' => 'venezuela', 'name' => 'Venezuela', 'code' => 'VE', 'order' => 1]
];
